<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>roole</string>
		<string>roo</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Roole</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\$[a-z0-9A-Z_-]+)\s*=\s*(@function)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.roole</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>{</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable_assignment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.scss</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@keyframes)\s+.*?\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\d+%|from|to)\s*{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\@[a-z-]+</string>
			<key>name</key>
			<string>keyword.control.at-rule.css</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.|#|\[)[^ ){]+</string>
			<key>name</key>
			<string>constant.other.color.css</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$[a-z0-9A-Z_-]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.roole</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-z0-9A-Z_-]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b</string>
					<key>name</key>
					<string>constant.numeric.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(-|\+)?([0-9]*\.[0-9]+|[0-9]+)([a-z+]+|%)?</string>
					<key>name</key>
					<string>constant.numeric.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z][A-Za-z._-]*</string>
					<key>name</key>
					<string>constant.numeric.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>constant.numeric.css</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>[a-zA-Z-]+\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>punctuation.function.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\$[a-z0-9A-Z_-]+</string>
			<key>name</key>
			<string>variable.roole</string>
		</dict>
		<key>variable_assignment</key>
		<dict>
			<key>begin</key>
			<string>(\$[a-z0-9A-Z_-]+)\s*=\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.roole</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.roole</string>
	<key>uuid</key>
	<string>70ff33f0-f096-11e2-b778-0800200c9a66</string>
</dict>
</plist>
